// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';
import {main} from '../models';

export function ClearSync():Promise<void>;

export function Install():Promise<installer.Result>;

export function Look():Promise<installer.State>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function RevealExtension():Promise<void>;

export function SetSync(arg1:string,arg2:string):Promise<main.SyncOutcome>;

export function Settings():Promise<main.Settings>;
