// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtensionDir() {
  return window['go']['main']['App']['ExtensionDir']();
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function Look() {
  return window['go']['main']['App']['Look']();
}
