// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function ClearSync() {
  return window['go']['main']['App']['ClearSync']();
}

export function DiagnoseSync() {
  return window['go']['main']['App']['DiagnoseSync']();
}

export function DismissUpdate(arg1) {
  return window['go']['main']['App']['DismissUpdate'](arg1);
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function Look() {
  return window['go']['main']['App']['Look']();
}

export function OpenChapter(arg1) {
  return window['go']['main']['App']['OpenChapter'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenUpdatePage() {
  return window['go']['main']['App']['OpenUpdatePage']();
}

export function PublicAddress() {
  return window['go']['main']['App']['PublicAddress']();
}

export function RetrySync() {
  return window['go']['main']['App']['RetrySync']();
}

export function RevealExtension() {
  return window['go']['main']['App']['RevealExtension']();
}

export function SetChapterBrowser(arg1) {
  return window['go']['main']['App']['SetChapterBrowser'](arg1);
}

export function SetSync(arg1, arg2) {
  return window['go']['main']['App']['SetSync'](arg1, arg2);
}

export function SetSyncFields(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSyncFields'](arg1, arg2, arg3, arg4);
}

export function SetUpdateChecks(arg1) {
  return window['go']['main']['App']['SetUpdateChecks'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function UseStoredSync(arg1) {
  return window['go']['main']['App']['UseStoredSync'](arg1);
}
